version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
        links:
            - php
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
        links:
            - mysql
    mysql:
        image: mariadb:latest
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_USER: 'tuantq'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'php8-db'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: pma
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80
volumes:
    mysqldata: {}